"""Initial migration

Revision ID: 01499ee036ee
Revises: 
Create Date: 2026-03-14 18:55:45.528850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01499ee036ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('lid_number', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('domicile', sa.String(length=100), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_alias', sa.String(length=100), nullable=True),
    sa.Column('unit_qty', sa.Integer(), nullable=True),
    sa.Column('is_b2b', sa.Boolean(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('human_takeover', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_lid_number'), 'customers', ['lid_number'], unique=True)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('installation_type', sa.String(length=50), nullable=False),
    sa.Column('can_shutdown_engine', sa.Boolean(), nullable=True),
    sa.Column('is_realtime_tracking', sa.Boolean(), nullable=True),
    sa.Column('ecommerce_links', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('compatibility', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('message_role', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_customer_id'), 'chat_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('customer_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_actions_customer_id'), 'customer_actions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_actions_id'), 'customer_actions', ['id'], unique=False)
    op.create_table('customer_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('meeting_datetime', sa.DateTime(), nullable=True),
    sa.Column('meeting_format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_meetings_customer_id'), 'customer_meetings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_meetings_id'), 'customer_meetings', ['id'], unique=False)
    op.create_table('intent_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('product_keywords', sa.JSON(), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('message_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_classifications_customer_id'), 'intent_classifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_intent_classifications_id'), 'intent_classifications', ['id'], unique=False)
    op.create_index(op.f('ix_intent_classifications_intent'), 'intent_classifications', ['intent'], unique=False)
    op.create_table('leads_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('route_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_routing_customer_id'), 'leads_routing', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_routing_id'), 'leads_routing', ['id'], unique=False)
    op.create_table('product_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('unit_qty', sa.Integer(), nullable=True),
    sa.Column('recommended_product', sa.String(length=200), nullable=True),
    sa.Column('ecommerce_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_inquiries_customer_id'), 'product_inquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_inquiries_id'), 'product_inquiries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_inquiries_id'), table_name='product_inquiries')
    op.drop_index(op.f('ix_product_inquiries_customer_id'), table_name='product_inquiries')
    op.drop_table('product_inquiries')
    op.drop_index(op.f('ix_leads_routing_id'), table_name='leads_routing')
    op.drop_index(op.f('ix_leads_routing_customer_id'), table_name='leads_routing')
    op.drop_table('leads_routing')
    op.drop_index(op.f('ix_intent_classifications_intent'), table_name='intent_classifications')
    op.drop_index(op.f('ix_intent_classifications_id'), table_name='intent_classifications')
    op.drop_index(op.f('ix_intent_classifications_customer_id'), table_name='intent_classifications')
    op.drop_table('intent_classifications')
    op.drop_index(op.f('ix_customer_meetings_id'), table_name='customer_meetings')
    op.drop_index(op.f('ix_customer_meetings_customer_id'), table_name='customer_meetings')
    op.drop_table('customer_meetings')
    op.drop_index(op.f('ix_customer_actions_id'), table_name='customer_actions')
    op.drop_index(op.f('ix_customer_actions_customer_id'), table_name='customer_actions')
    op.drop_table('customer_actions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_customer_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_lid_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
